### ISSUE TITLE
can't build skipper (skipper build cmd) with v2.0.0 and v2.0.1

### ISSUE THREAD

**Issue by nmagnezi** [Stratoscale/skipper#163]
See $TOPIC.

I get:

# skipper build
```python
WARNING:root:*** Uncommitted changes present - Build container version might be outdated ***
[skipper] Building image: assisted-service-build
INFO:skipper:Building image: assisted-service-build
Traceback (most recent call last):
  File "/usr/local/bin/skipper", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/skipper/main.py", line 12, in main
    return_code = cli.cli(
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/skipper/cli.py", line 117, in build
    fqdn_image = image + ':' + tag
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by nmagnezi** [comment]
Python 3.9.6

**Comment by nmagnezi** [comment]
same result with Python 3.11.4

**Comment by nmagnezi** [comment]
last working version for me: 1.34.0

**Comment by eifrach** [comment]
had the same issue - I changed this line
https://github.com/Stratoscale/skipper/blob/upstream/skipper/cli.py#L117

```python
fqdn_image = image + ':' + tag.decode('utf-8')
```

```console
> skipper version; python --version
2.0.1
Python 3.11.4
```

on version 1.34.0
the line was decoded 
https://github.com/Stratoscale/skipper/blob/1.34.0/skipper/git.py#L19

on new verison is isn't 
https://github.com/Stratoscale/skipper/blob/2.0.1/skipper/git.py#L19
